micronaut:
  application:
    name: micronaut-transferex-api
  server:
    port: 6161
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger

jackson:
  default-property-inclusion: non_null

datasources:
  default:
    url: jdbc:h2:mem:transferexDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
jpa:
  default:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update
        show_sql: false
        format_sql: true


application:
  error:
    default-exception-message: Beklenmeyen bir hata oluştu
    access-denied: Üye girişi yapmalısınız.
    basket-item-not-updated: Sepet ürün sayısı güncellenemedi.
  api:
    swagger:
      path: /api-docs/swagger
      version: 3.19.4
      layout: StandaloneLayout
      deepLinking: true
      urls:
        - name: ubw-rest
          url: /api-docs/swagger/micronaut-transferex-api-1.0.yml
